services:
  - type: web
    name: sales-prediction-app
    env: python
    build:
      pythonVersion: 3.11.7
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.routes:app
    envVars:
      - key: SECRET_KEY
        fromService:
          name: sales-prediction-app
          type: env
          property: secret_key
      - key: SUPABASE_URL
        fromService:
          name: sales-prediction-app
          type: env
          property: supabase_url
      - key: SUPABASE_KEY
        fromService:
          name: sales-prediction-app
          type: env
          property: supabase_key
